### PR TITLE
removed unnecessary env variables 

### PR DESCRIPTION
**Pull request by ivanfslee**
removed unnecessary env variables

### CODE REVIEW

**Review by ChaseSobey — APPROVED** [review]
I love when clutter is removed!!

**Review by taronavagyan — CHANGES_REQUESTED** [review]
Can you add a REGION property to embrasureServerlessEnvVariables with the same value as AWS_REGION?

**Comment by ivanfslee** [comment]
Ok, will do.

**Review by taronavagyan — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
