### PR TITLE
Wrapper

### PR DESCRIPTION
**Pull request by taronavagyan**
Edited wrapper to work as a module. Created an index.js file which retrieves secrets and injects them using hard-coded positions for command line arguments. 

Example of injecting secrets into `test.js` would be :
`node index.js -- test.js`

### CODE REVIEW

**Comment by ChaseSobey** [comment]
Can you explain what you mean by you edited the wrapper to work as a module?

**Comment by taronavagyan** [comment]
> Can you explain what you mean by you edited the wrapper to work as a module?

Sure, wrapper.js now exports a function that takes three arguments for node's absolute path, the path of the file to inject secrets into, and the `env` object, as opposed to those parameters being hard-coded test values earlier.

**Review by ChaseSobey — APPROVED** [review]
Ok makes sense, Thanks!

**Review by ivanfslee — APPROVED** [review]
Everything looks okay.

**Pull request merged**
